name: combopt
channels:
  - pyg
  - gurobi
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gurobi=11.0.3=py310_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lightning=2.4.0=pyhd8ed1ab_0
  - lightning-utilities=0.11.6=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pyg=2.5.2=py310_torch_2.2.0_cu118
  - python=3.10.14=h955ad1f_1
  - pytorch=2.2.2=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cluster=1.6.3=py310_torch_2.2.0_cu118
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.4.0=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.2.0_cu118
  - pytorch-sparse=0.6.18=py310_torch_2.2.0_cu118
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchtriton=2.2.0=py310
  - typing_extensions=4.11.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - aiohttp==3.9.5
    - antlr4-python3-runtime==4.8
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - axial-positional-embedding==0.2.1
    - brotli==1.0.9
    - certifi==2024.7.4
    - cftime==1.6.4
    - click==8.1.7
    - cloudpickle==3.0.0
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - dask==2024.8.1
    - debugpy==1.8.7
    - decorator==5.1.1
    # - dgl==2.4.0+cu118
    - dimod==0.12.16
    - docker-pycreds==0.4.0
    - dwave-networkx==0.8.15
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - filelock==3.13.1
    - fonttools==4.53.1
    - frozenlist==1.4.0
    - fsspec==2024.3.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.1.2
    - gputil==1.4.0
    - gurobipy==11.0.3
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.2.0
    - idna==3.7
    - importlib-metadata==8.2.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipykernel==6.29.5
    - ipython==8.28.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.5
    - littleutils==0.2.4
    - llvmlite==0.43.0
    - local-attention==1.9.14
    - locket==1.0.0
    - loguru==0.7.2
    - markupsafe==2.1.3
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - nest-asyncio==1.6.0
    - netcdf4==1.7.1.post2
    - networkx==3.3
    - numba==0.60.0
    - numpy==1.26.4
    - ogb==1.3.6
    - omegaconf==2.1.2
    - outdated==0.2.2
    - pandas==2.2.2
    - parso==0.8.4
    - partd==1.4.2
    - performer-pytorch==1.1.4
    - pexpect==4.9.0
    - pillow==10.4.0
    - pip==24.2
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - portalocker==2.10.1
    - prompt-toolkit==3.0.48
    - protobuf==5.27.3
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pygments==2.18.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - pytest==8.3.2
    - python-dateutil==2.9.0.post0
    - python-sat==1.8.dev13
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.2.0
    - requests==2.32.3
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - sentry-sdk==2.13.0
    - setproctitle==1.3.3
    - setuptools==72.1.0
    - six==1.16.0
    - smmap==5.0.1
    - stack-data==0.6.3
    - submitit==1.5.2
    - sympy==1.12
    - threadpoolctl==3.5.0
    - tomli==2.0.1
    - toolz==0.12.1
    - torch==2.2.2
    - torch-cluster==1.6.3
    - torch-geometric==2.5.2
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torchaudio==2.2.2
    - torchdata==0.9.0
    - torchvision==0.15.2
    - tornado==6.4.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - triton==2.2.0
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - urllib3==2.2.2
    - visdom==0.2.4
    - wandb==0.17.7
    - wcwidth==0.2.13
    - websocket-client==1.8.0
    - wheel==0.43.0
    - xarray==2024.7.0
    - yacs==0.1.8
    - yarl==1.9.3
    - zipp==3.20.0
