area-constraint: 0.1
ccpso:
  c: 1
  group_sizes:
  - 5
  - 10
  - 20
  iterations: 1000
  n_individuals: 500
  verbose: 500
clpso:
  c: 1
  iterations: 1000
  n_individuals: 500
  verbose: 500
comm-scale-factor: 1.0
dbpso:
  c1: 0.575
  c2: 0.1
  iterations: 1000
  k: 4
  n_particles: 500
  p: 2
  verbose: true
  w: 1.05
esa:
  iter: 10000
  verbose: 500
gl25:
  iter: 10000
  n_pop: 500
  verbose: 500
graph-file: inputs/task_graph_topology/soda-benchmark-graphs/pytorch-graphs/squeeze_net_tosa.dot
hw-scale-factor: 0.3
hw-scale-variance: 0.5
jade:
  iter: 10000
  n_individuals: 500
  verbose: 500
opt-cost-type: spt
output-dir: outputs
pso:
  c1: 0.575
  c2: 0.1
  iterations: 1000
  n_particles: 500
  verbose: true
  w: 1.05
random:
  num_samples: 500
  p: 0.5
result-file-prefix: spt-opt
seed: 2
shade:
  iter: 10000
  n_individuals: 500
  verbose: 500
solution-dir: spt-opt-partitions
taskgraph-dir: inputs/task_graph_complete
